// Code generated by MockGen. DO NOT EDIT.
// Source: src/project/repositories/ayah_repository.go
//
// Generated by this command:
//
//	mockgen -source=src/project/repositories/ayah_repository.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	reflect "reflect"
	models "ulil-albab-be/src/project/models"

	gomock "go.uber.org/mock/gomock"
)

// MockAyahRepo is a mock of AyahRepo interface.
type MockAyahRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAyahRepoMockRecorder
	isgomock struct{}
}

// MockAyahRepoMockRecorder is the mock recorder for MockAyahRepo.
type MockAyahRepoMockRecorder struct {
	mock *MockAyahRepo
}

// NewMockAyahRepo creates a new mock instance.
func NewMockAyahRepo(ctrl *gomock.Controller) *MockAyahRepo {
	mock := &MockAyahRepo{ctrl: ctrl}
	mock.recorder = &MockAyahRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAyahRepo) EXPECT() *MockAyahRepoMockRecorder {
	return m.recorder
}

// GetAllAyat mocks base method.
func (m *MockAyahRepo) GetAllAyat() ([]models.AyatResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAyat")
	ret0, _ := ret[0].([]models.AyatResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAyat indicates an expected call of GetAllAyat.
func (mr *MockAyahRepoMockRecorder) GetAllAyat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAyat", reflect.TypeOf((*MockAyahRepo)(nil).GetAllAyat))
}

// GetAyatBySuratId mocks base method.
func (m *MockAyahRepo) GetAyatBySuratId(arg0 int) ([]models.AyatResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAyatBySuratId", arg0)
	ret0, _ := ret[0].([]models.AyatResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAyatBySuratId indicates an expected call of GetAyatBySuratId.
func (mr *MockAyahRepoMockRecorder) GetAyatBySuratId(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAyatBySuratId", reflect.TypeOf((*MockAyahRepo)(nil).GetAyatBySuratId), arg0)
}
